# Explicit proxy placement avoids depending on optional OR-Tools SCIP in RTLMP.
place_macro -macro_name {u_farm.gen_stat_mem\[0\].u_mem.u_macro} -location {50 50} -orientation R0
place_macro -macro_name {u_farm.gen_stat_mem\[1\].u_mem.u_macro} -location {675 50} -orientation R0
place_macro -macro_name {u_farm.gen_stat_mem\[2\].u_mem.u_macro} -location {1300 50} -orientation R0
place_macro -macro_name {u_farm.gen_stat_mem\[3\].u_mem.u_macro} -location {1925 50} -orientation R0
place_macro -macro_name {u_farm.gen_stat_mem\[4\].u_mem.u_macro} -location {50 190} -orientation R0
place_macro -macro_name {u_farm.gen_stat_mem\[5\].u_mem.u_macro} -location {675 190} -orientation R0
place_macro -macro_name {u_farm.gen_stat_mem\[6\].u_mem.u_macro} -location {1300 190} -orientation R0
place_macro -macro_name {u_farm.gen_stat_mem\[7\].u_mem.u_macro} -location {1925 190} -orientation R0
place_macro -macro_name {u_farm.gen_stat_mem\[8\].u_mem.u_macro} -location {50 330} -orientation R0
place_macro -macro_name {u_farm.gen_stat_mem\[9\].u_mem.u_macro} -location {675 330} -orientation R0
place_macro -macro_name {u_farm.gen_stat_mem\[10\].u_mem.u_macro} -location {1300 330} -orientation R0
place_macro -macro_name {u_farm.gen_stat_mem\[11\].u_mem.u_macro} -location {1925 330} -orientation R0
place_macro -macro_name {u_farm.gen_stat_mem\[12\].u_mem.u_macro} -location {50 470} -orientation R0
place_macro -macro_name {u_farm.gen_stat_mem\[13\].u_mem.u_macro} -location {675 470} -orientation R0
place_macro -macro_name {u_farm.gen_stat_mem\[14\].u_mem.u_macro} -location {1300 470} -orientation R0
place_macro -macro_name {u_farm.gen_stat_mem\[15\].u_mem.u_macro} -location {1925 470} -orientation R0
place_macro -macro_name {u_farm.gen_stat_mem\[16\].u_mem.u_macro} -location {50 610} -orientation R0
place_macro -macro_name {u_farm.gen_stat_mem\[17\].u_mem.u_macro} -location {675 610} -orientation R0
place_macro -macro_name {u_farm.gen_stat_mem\[18\].u_mem.u_macro} -location {1300 610} -orientation R0
place_macro -macro_name {u_farm.gen_stat_mem\[19\].u_mem.u_macro} -location {1925 610} -orientation R0
place_macro -macro_name {u_farm.gen_stat_mem\[20\].u_mem.u_macro} -location {50 750} -orientation R0
place_macro -macro_name {u_farm.gen_stat_mem\[21\].u_mem.u_macro} -location {675 750} -orientation R0
place_macro -macro_name {u_farm.gen_stat_mem\[22\].u_mem.u_macro} -location {1300 750} -orientation R0
place_macro -macro_name {u_farm.gen_stat_mem\[23\].u_mem.u_macro} -location {1925 750} -orientation R0
place_macro -macro_name {u_farm.gen_stat_mem\[24\].u_mem.u_macro} -location {50 890} -orientation R0
place_macro -macro_name {u_farm.gen_stat_mem\[25\].u_mem.u_macro} -location {675 890} -orientation R0
place_macro -macro_name {u_farm.gen_stat_mem\[26\].u_mem.u_macro} -location {1300 890} -orientation R0
place_macro -macro_name {u_farm.gen_stat_mem\[27\].u_mem.u_macro} -location {1925 890} -orientation R0
place_macro -macro_name {u_farm.gen_stat_mem\[28\].u_mem.u_macro} -location {50 1030} -orientation R0
place_macro -macro_name {u_farm.gen_stat_mem\[29\].u_mem.u_macro} -location {675 1030} -orientation R0
place_macro -macro_name {u_farm.gen_stat_mem\[30\].u_mem.u_macro} -location {1300 1030} -orientation R0
place_macro -macro_name {u_farm.gen_stat_mem\[31\].u_mem.u_macro} -location {1925 1030} -orientation R0
place_macro -macro_name {u_farm.gen_stat_mem\[32\].u_mem.u_macro} -location {50 1170} -orientation R0
place_macro -macro_name {u_farm.gen_stat_mem\[33\].u_mem.u_macro} -location {675 1170} -orientation R0
